# Generated by Django 6.0.2 on 2026-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_can_a_user_can_ab_user_can_ac_user_can_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
    ]
