# Generated by Django 6.0.2 on 2026-02-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_a',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_ab',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_ac',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_b',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_bc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_box',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_c',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_super',
        ),
    ]
