# Generated by Django 6.0.2 on 2026-02-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_can_a_remove_user_can_ab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit_limit',
        ),
    ]
