# Generated by Django 6.0.2 on 2026-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_count_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
