# Generated by Django 6.0.2 on 2026-02-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_credit_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
