# Generated by Django 6.0.2 on 2026-02-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_ab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_ac',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_bc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_box',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_super',
            field=models.IntegerField(default=0),
        ),
    ]
