# Generated by Django 6.0.2 on 2026-02-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_count_a_user_count_ab_user_count_ac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10)),
                ('max_count', models.IntegerField(default=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_limits', to='core.game')),
            ],
            options={
                'unique_together': {('game', 'number', 'type')},
            },
        ),
    ]
