# Generated by Django 6.0.2 on 2026-02-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_daily_limit_remove_user_weekly_limit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='numberlimit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='numberlimit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='number_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='numberlimit',
            unique_together={('user', 'game', 'number', 'type')},
        ),
    ]
