# Generated by Django 6.0.2 on 2026-02-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_numberlimit_unique_together_numberlimit_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='credit_limit',
            new_name='weekly_credit_limit',
        ),
    ]
