# Generated by Django 6.0.2 on 2026-02-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_credit_limit_user_weekly_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
