# Generated by Django 4.2.19 on 2026-02-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_price_a_user_price_ab_user_price_ac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='price_a',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price_ab',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price_ac',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price_b',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price_bc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price_box',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price_c',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price_super',
        ),
        migrations.AddField(
            model_name='user',
            name='price_ab_bc_ac',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='price_abc',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='price_super_box',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
