# Generated by Django 4.2.19 on 2026-02-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_user_price_a_remove_user_price_ab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
