# Generated by Django 4.2.19 on 2026-02-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_gametiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='complimentary_numbers',
            field=models.TextField(blank=True, help_text='Paste 30 complimentary numbers here', null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='fifth_prize',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='fourth_prize',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='second_prize',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='third_prize',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='winning_number',
            field=models.CharField(help_text='1st Prize', max_length=3),
        ),
    ]
