# Generated by Django 4.2.19 on 2026-02-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_gameresult_complimentary_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='price_super_box',
        ),
        migrations.AddField(
            model_name='user',
            name='price_box',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='price_super',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='price_ab_bc_ac',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='price_abc',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=10),
        ),
    ]
