# Generated by Django 4.2.19 on 2026-02-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_user_price_super_box_user_price_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comm_6th',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_ab_bc_ac_1',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_abc_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_box_2s_1',
            field=models.DecimalField(decimal_places=2, default=330.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_box_2s_2',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_box_3d_1',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_box_3d_2',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_box_3s_1',
            field=models.DecimalField(decimal_places=2, default=450.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_super_1',
            field=models.DecimalField(decimal_places=2, default=400.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_super_2',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_super_3',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_super_4',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='comm_super_5',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_6th',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_ab_bc_ac_1',
            field=models.DecimalField(decimal_places=2, default=700.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_abc_1',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_box_2s_1',
            field=models.DecimalField(decimal_places=2, default=3800.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_box_2s_2',
            field=models.DecimalField(decimal_places=2, default=1600.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_box_3d_1',
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_box_3d_2',
            field=models.DecimalField(decimal_places=2, default=800.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_box_3s_1',
            field=models.DecimalField(decimal_places=2, default=7000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_super_1',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_super_2',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_super_3',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_super_4',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prize_super_5',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
