# Generated by Django 4.2.19 on 2026-02-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_comm_6th_user_comm_ab_bc_ac_1_user_comm_abc_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sales_comm_ab_bc_ac',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='sales_comm_abc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='sales_comm_box',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='sales_comm_super',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
