# Generated by Django 4.2.19 on 2026-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_sales_comm_ab_bc_ac_user_sales_comm_abc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='global_count_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='global_count_ab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='global_count_ac',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='global_count_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='global_count_bc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='global_count_box',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='global_count_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='global_count_super',
            field=models.IntegerField(default=0),
        ),
    ]
