# Generated by Django 4.2.19 on 2026-03-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_game_global_count_a_game_global_count_ab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNumberLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10)),
                ('max_count', models.IntegerField(default=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_number_limits', to='core.game')),
            ],
            options={
                'unique_together': {('game', 'number', 'type')},
            },
        ),
    ]
