# Generated by Django 4.2.19 on 2026-03-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_color',
            field=models.CharField(default='#1e3799', max_length=7),
        ),
    ]
