# Generated by Django 4.2.19 on 2026-03-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_user_app_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='app_color',
        ),
    ]
