# Generated by Django 4.2.19 on 2026-03-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_user_app_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameTiming',
        ),
    ]
