# Generated by Django 4.2.19 on 2026-03-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_gametiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_time',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
