# Generated by Django 4.2.19 on 2026-03-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_game_end_time_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='winning_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
