# Generated by Django 4.2.19 on 2026-03-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_bet_winning_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='winning_prize_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
