# Generated by Django 4.2.19 on 2026-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_usergametiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='color',
            field=models.CharField(default='#2C3E50', max_length=20),
        ),
    ]
