# Generated by Django 4.2.19 on 2026-03-04 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_game_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='globalnumberlimit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='globalnumberlimit',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_number_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='globalnumberlimit',
            unique_together={('admin', 'game', 'number', 'type')},
        ),
    ]
