# Generated by Django 4.2.19 on 2026-03-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_globalnumberlimit_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
