# Generated by Django 4.2.19 on 2026-03-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_user_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_delete_invoice', models.BooleanField(default=True)),
                ('edit_delete_limit_time', models.TimeField(default='23:59:59')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='can_edit_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='edit_delete_limit_time',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='winning_prize_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
