# Generated by Django 4.2.19 on 2026-03-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_systemsettings_game_can_edit_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_games',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='core.game'),
        ),
    ]
