# Generated by Django 6.0.5 on 2026-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_user_allowed_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='state',
            field=models.CharField(default='KL', max_length=5),
        ),
    ]
