# Generated by Django 6.0.5 on 2026-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_bet_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tn_price_ab_bc_ac',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_price_abc',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_price_box',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_price_super',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_ab_bc_ac',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_abc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_box',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_super',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
