# Generated by Django 6.0.5 on 2026-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_user_tn_price_ab_bc_ac_user_tn_price_abc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tn_price_box',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tn_price_super',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tn_sales_comm_box',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tn_sales_comm_super',
        ),
        migrations.AddField(
            model_name='user',
            name='tn_price_3d_10',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_price_3d_25',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_price_3d_30',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_price_3d_60',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_price_4d_110',
            field=models.DecimalField(decimal_places=2, default=110.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_price_4d_20',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_price_4d_55',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_3d_10',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_3d_25',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_3d_30',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_3d_60',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_4d_110',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_4d_20',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_sales_comm_4d_55',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
