# Generated by Django 6.0.5 on 2026-08-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_user_tn_price_box_remove_user_tn_price_super_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='options_bg_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
