# Generated by Django 6.0.2 on 2026-08-18 16:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_game_options_bg_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='KL', max_length=5)),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10)),
                ('number', models.CharField(max_length=3)),
                ('count', models.IntegerField()),
                ('price_per_count', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comm_per_count', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_auto', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(blank=True, null=True)),
                ('winning_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('forwarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_out', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_in', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='ForwardLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10)),
                ('number', models.CharField(blank=True, help_text='Optional: If blank, applies to all numbers of this type', max_length=3, null=True)),
                ('max_retained_count', models.IntegerField(default=100)),
                ('state', models.CharField(default='KL', max_length=5)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_limits', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
            ],
            options={
                'unique_together': {('admin', 'game', 'type', 'state', 'number')},
            },
        ),
    ]
