# Generated by Django 6.0.2 on 2026-08-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_forwardedbet_forwardlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardedbet',
            name='winning_prize_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
