# Generated by Django 6.0.2 on 2026-08-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_forwardedbet_winning_prize_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='fifth_prize',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='fourth_prize',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='second_prize',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='third_prize',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='winning_number',
            field=models.CharField(help_text='1st Prize', max_length=10),
        ),
    ]
