# Generated by Django 6.0.2 on 2026-08-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_gameresult_fifth_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tn_prize_3d_10',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_3d_10_bc',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_3d_25',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_3d_25_bc',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_3d_30',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_3d_30_bc',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_3d_30_c',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_3d_60',
            field=models.DecimalField(decimal_places=2, default=30000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_3d_60_bc',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_3d_60_c',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_4d_110_1',
            field=models.DecimalField(decimal_places=2, default=450000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_4d_110_2',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_4d_110_3',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_4d_110_4',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_4d_20_1',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_4d_55_1',
            field=models.DecimalField(decimal_places=2, default=225000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_4d_55_2',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_4d_55_3',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_4d_55_4',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_ab_bc_ac',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tn_prize_abc',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
