# Generated by Django 6.0.2 on 2026-08-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_user_tn_prize_3d_10_user_tn_prize_3d_10_bc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clearedexposure',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='forwardedbet',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='forwardlimit',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='globalnumberlimit',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='numberlimit',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
    ]
