# Generated by Django 6.0.2 on 2026-08-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_bet_type_alter_clearedexposure_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('KL', 'KL'), ('TN', 'TN')], default='KL', max_length=5),
        ),
    ]
