# Generated by Django 6.0.2 on 2026-08-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_game_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.AlterField(
            model_name='bet',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('3D-10', '3D-10'), ('3D-25', '3D-25'), ('3D-30', '3D-30'), ('3D-60', '3D-60'), ('4D-110', '4D-110'), ('4D-55', '4D-55'), ('4D-20', '4D-20'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clearedexposure',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clearedexposure',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('3D-10', '3D-10'), ('3D-25', '3D-25'), ('3D-30', '3D-30'), ('3D-60', '3D-60'), ('4D-110', '4D-110'), ('4D-55', '4D-55'), ('4D-20', '4D-20'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='forwardedbet',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='forwardedbet',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('3D-10', '3D-10'), ('3D-25', '3D-25'), ('3D-30', '3D-30'), ('3D-60', '3D-60'), ('4D-110', '4D-110'), ('4D-55', '4D-55'), ('4D-20', '4D-20'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='forwardedbet',
            name='winning_prize_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='forwardlimit',
            name='number',
            field=models.CharField(blank=True, help_text='Optional: If blank, applies to all numbers of this type', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='forwardlimit',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('3D-10', '3D-10'), ('3D-25', '3D-25'), ('3D-30', '3D-30'), ('3D-60', '3D-60'), ('4D-110', '4D-110'), ('4D-55', '4D-55'), ('4D-20', '4D-20'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='globalnumberlimit',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='globalnumberlimit',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('3D-10', '3D-10'), ('3D-25', '3D-25'), ('3D-30', '3D-30'), ('3D-60', '3D-60'), ('4D-110', '4D-110'), ('4D-55', '4D-55'), ('4D-20', '4D-20'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='numberlimit',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='numberlimit',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC'), ('TN-A', 'TN-A'), ('TN-B', 'TN-B'), ('TN-C', 'TN-C'), ('TN-AB', 'TN-AB'), ('TN-BC', 'TN-BC'), ('TN-AC', 'TN-AC'), ('3D-10', '3D-10'), ('3D-25', '3D-25'), ('3D-30', '3D-30'), ('3D-60', '3D-60'), ('4D-110', '4D-110'), ('4D-55', '4D-55'), ('4D-20', '4D-20'), ('SUPER', 'SUPER'), ('BOX', 'BOX')], max_length=10),
        ),
    ]
