# Generated by Django 6.0.5 on 2026-08-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_game_global_tn_count_3d_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
