# Generated by Django 6.0.5 on 2026-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_bet_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_forward',
            field=models.BooleanField(default=False),
        ),
    ]
