# Generated by Django 6.0.5 on 2026-09-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_user_can_forward'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='state',
            field=models.CharField(choices=[('KL', 'Kerala'), ('TN', 'Tamil Nadu')], default='KL', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='gameresult',
            unique_together={('game', 'date', 'state')},
        ),
    ]
